/* Generated By:JavaCC: Do not edit this line. SimpleJsonConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleJsonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int EXPONENT = 6;
  /** RegularExpression Id. */
  int WORD_TOKEN = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int LEFT_OBJ = 9;
  /** RegularExpression Id. */
  int RIGHT_OBJ = 10;
  /** RegularExpression Id. */
  int LEFT_ARR = 11;
  /** RegularExpression Id. */
  int RIGHT_ARR = 12;
  /** RegularExpression Id. */
  int QUOTE = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int NULL = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<WORD_TOKEN>",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "\":\"",
    "<BOOLEAN>",
    "\"null\"",
    "\"exit\"",
  };

}
