apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page
spec:
  selector:
    matchLabels:
      app: meudeployment
  replicas: 5
  template:
    metadata:
      labels:
        app: meudeployment
    spec:
      containers:
        - name: http
          image: fabricioveronez/web-page:blue
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: web-page
spec:
  selector:
    app: meudeployment
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30000
  type: NodePort


