apiVersion: v1
kind: Pod
metadata:
  name: my-cm-pod-vol
spec:
  containers:
    - image:  nginx
      name:  my-container
      envFrom:
        - configMapRef:
            name: my-cm
      volumeMounts:
        - name: my-vol
          mountPath: "/etc/my-vol"
          readOnly: true

  volumes:
    - name: my-vol
      configMap:
        name: my-cm


      



