apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  suspend: false
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 10
  schedule: "* * * * *"
  jobTemplate:
    spec:
      completions: 10
      completionMode: "Indexed"
      parallelism: 5
      template:
        spec:
          containers:
            - name: my-container-busybox
              image: busybox
              command: 
                - "bin/sh"
                - "-c"
                - "for i in 1 2; do echo Lucy number $i = $(( 1 + RANDOM % 70)); done"
          restartPolicy: Never

