apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  # Connection database config
  my.config.db: |
    database: "mariadb"
    database_uri: "mysql://localhost:3306"
  test.field: "hello!"
  test2: "teste 2"
immutable: true
    
    
