apiVersion: v1
kind: ConfigMap
metadata:
  name: my-cm
data:
  # Connection database config
  my.config.db: |
    database: "mariadb"
    database_uri: "mariadb://localhost:3306"

  test.field: "hello"
    
    
