apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
spec:
  containers:
    - name: my-nginx
      image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-apache
spec:
  containers:
    - name: my-apache
      image: httpd
  
      

