apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-server
  labels:
    app: my-nginx-server
spec:
  containers:
  - name: nginx
    image: docker.io/nginx
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
      limits:
        cpu: "1m"
        memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-server-svc
spec:
  selector:
    app: my-nginx-server
  ports:
  - name:  http
    port:  80
    protocol: TCP






  