apiVersion: v1
kind: Pod
metadata:
  name: pod-optional-secret-vol-env
spec:
  containers:
    - name: my-container
      image: nginx
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: my-secret
            optional: true
      volumeMounts:
        - mountPath: "/etc/my-vol"
          name: my-vol

  volumes:
    - name: my-vol
      secret:
        secretName: my-secret
        optional: true


  