apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  # aqui é obrigatórios os valores serem em base64
  user: "YWRtaW4="
  pass: "TXktcGFzcy0xMjMK"
stringData:
  my-database-name: "mysql"

# Secret assim como configmaps pode ser imutável
immutable: true
