apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-pod
spec:
  containers:
    - name: redis-pod
      image: redis
      volumeMounts:
        - mountPath: "/my-volume"
          name: "cache-storage"

  volumes:
    - name: cache-storage
      emptyDir: {}


