apiVersion: v1
kind: Service
metadata:
  name:  nginx
  labels:
    app: nginx
spec:
  selector:
    app:  nginx
  type:  ClusterIP
  clusterIP: None
  ports:
  - name:  http
    port:  80
    targetPort:  8080
  


