apiVersion: v1
kind: Service
metadata:
  name: svc-sts
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: nginx-app-pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  selector:
    matchLabels:
      app: nginx-app-pods
  serviceName: "svc-sts"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app-pods
    spec:
      containers:
      - name: my-container
        image: nginx:1.22
        volumeMounts:
        - name: my-pv
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: my-pv
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi          
