apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    type: web-app
spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-webservice-nodeport
spec:
  type: NodePort
  selector:
    type: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    NodePort: 3008
---
apiVersion: v1
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080      


      
           



